import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

import "remixicon/fonts/remixicon.css";
import Footer from "@/components/Footer";
import ScrollToTop from "@/components/ScrollToTop";
import PreLoader from "@/components/PreLoader";

const fontPoppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata = {
  title: "PT.Permata Shipping Line",
  description: "Generated by Prime",
  icons: {
    icon: "/favicon.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={`${fontPoppins.className} antialiased`} id="beranda">
        <PreLoader />
        <ScrollToTop />
        <Navbar />

        <div className="container mx-auto px-4">{children}</div>

        <Footer />
      </body>
    </html>
  );
}
